server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://my-postgresql:5432/jwt_security
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: OF2Gu99S51
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql : true
    properties:
      hibernate:
        format_sql : true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 600000
      refresh-token:
        expiration: 86400000